/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Tue May 31 08:55:31 2016"
#define BUILD_TIME (1464699331L)

#define VERSION_NUMBER 0x03060002UL
#define VERSION_FEATURES 0x00060040UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c617eUL
#define VERSION_SANITY2 0x148c24958UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.6.0"
#define VERSION_ID \
 "Unix NetHack Version 3.6.0 - last build Tue May 31 08:55:31 2016."
#define JVERSION_ID \
 "Unix JNetHack Version 3.6.0-0.5."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.0 Unix, built May 31 08:55:31 2016."

